#!/usr/bin/python

#!Catching Errors

digit = float(input("Enter a Digit: "))
print(digit)

#! The above code is going to work just perfectly...

#!Try Except blocks

try:
    number = int(input("Enter a Number: "))
    print(number)
except:
    print("Invalid Input")

#!the above code is going to work just fine but instead of python yelling to us, it going to give us a prompt inform of a comment


#!Go and Test it Out!!!!
